spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    

server:
  port: 8083
  
logging:
  level:
    org: 
      hibernate: 
        type:   
          descriptor:   
            sql:  
              BasicBinder: TRACE

  
mongodb:
  primary:
    host: localhost
    port: 27017
    database: distributedDB
  replica:
    host: localhost
    port: 27017
    database: distributedDB
    
